name: plato-parser
version: 0.1.0.0
github: "ksrky/plato-parser"
license: BSD3
author: "ksrk"
maintainer: "example@example.com"
copyright: "2022 ksrk"

extra-source-files:
  - README.md
  - CHANGELOG.md

build-tools:
  - alex
  - happy

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ksrky/plato-parser#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - haskeline
  - mtl
  - safe-exceptions
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  plato-parser-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - plato-parser
